---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name:
          - php
          - apache2
          - libapache2-mod-php
          - php-gd
          - php-ssh2
          - mysql-server-5.7
          - php-mysql
          - python3-mysqldb
        state: latest
      become: yes

    - name: 'Cria o banco do mysql'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: 'Cria o usuario do mysql'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: wordpress_db.*:ALL
        state: present
      become: yes


    # Forma de usar loop e variavel de uma maneira mais antiga
    #- name: 'Instala pacotes de dependencia do sistema operacional'
    #  apt:
    #    name: "{{ item }}"
    #    state: latest
    #  become: yes
    #  with_items:
    #    - php
    #    - apache2
    #    - libapache2-mod-php
    #    - php-gd
    #    - libssh2-php
    #    - php5-mcrypt
    #    - mysql-server-5.6
    #    - python-mysqldb
    #    - php5-mysql


    # Forma de configuracao item a item
    #- name: 'Instala o PHP'
    #  apt:
    #    name: php
    #    state: latest
    #  become: yes
    #- name: 'Instala o Apache2'
    #  apt:
    #    name: apache2
    #    state: latest
    #  become: yes
    #- name: 'Instala o modphp'
    #  apt:
    #    name: libapache2-mod-php
    #    state: latest
    #  become: yes
